const THEMES = [
  {
    "key": "everest",
    "name": "Everest",
    "category": "Nature",
    "icon": "images/nature/everest-theme/icon48.png",
    "description": "Inspired by the majestic heights and serene landscapes of Mount Everest, this light theme brings a crisp and calming presence to Chrome. Soft icy tones and clean, airy surfaces evoke snow-covered peaks and clear mountain skies, creating a browsing experience that feels fresh, focused, and easy on the eyes.",
    "chromeUiUrl": "https://chromewebstore.google.com/detail/kcldghlfficdfjjjcenephkkdkcjngic?utm_source=codigrate_extension",
    "preview": {
      "frame": "#CADAE0",
      "toolbar": "#FDFEFF",
      "accent": "#246A89",
      "frameText": "#0F172A",
      "toolbarText": "#0F172A",
      "activeTab": "#FDFEFF",
      "inactiveTab": "#B2C0C5",
      "omnibox": "#E9EAEB",
      "border": "#AEBBC1",
      "muted": "#626875",
      "weakFill": "#DCDEE1",
      "weakFillStronger": "#C9CBD0",
      "pageBg": "#FFFFFF",
      "pageLine": "#E2E3E5"
    }
  },
  {
    "key": "aurora-borealis",
    "name": "Aurora Borealis",
    "category": "Nature",
    "icon": "images/nature/aurora-borealis-theme/icon48.png",
    "description": "Inspired by the natural phenomena of the Aurora Borealis, this dark theme captures the majesty and mystery of the Arctic night sky. Deep blue-green tones shape the browser frame, while luminous accents echo the ethereal colors of the Northern Lights, creating a browsing atmosphere that feels immersive, calm, and vibrant.",
    "chromeUiUrl": "https://chromewebstore.google.com/detail/ggdeckhhnhopdjnnbngcflijkhnlodfk?utm_source=codigrate_extension",
    "preview": {
      "frame": "#1C3847",
      "toolbar": "#142B37",
      "accent": "#049682",
      "frameText": "#F8FAFC",
      "toolbarText": "#F8FAFC",
      "activeTab": "#142B37",
      "inactiveTab": "#455C68",
      "omnibox": "#30444F",
      "border": "#4E646F",
      "muted": "#919DA3",
      "weakFill": "#54656E",
      "weakFillStronger": "#74828A",
      "pageBg": "#1D333F",
      "pageLine": "#5A6B74"
    }
  },
  {
    "key": "sakura",
    "name": "Sakura",
    "category": "Nature",
    "icon": "images/nature/sakura-theme/icon48.png",
    "description": "Inspired by the enchanting softness of Sakura blossoms, this theme brings a delicate spring atmosphere to Chrome. Gentle pinks and muted complementary tones create a serene, polished browser experience that feels light, graceful, and easy to live with throughout the day.",
    "chromeUiUrl": "https://chromewebstore.google.com/detail/nnildobojpcnfhiihnjklleoimimmkcc?utm_source=codigrate_extension",
    "preview": {
      "frame": "#F8DBE6",
      "toolbar": "#FEFCFC",
      "accent": "#B54B66",
      "frameText": "#0F172A",
      "toolbarText": "#0F172A",
      "activeTab": "#FEFCFC",
      "inactiveTab": "#DAC1CA",
      "omnibox": "#EAE8E8",
      "border": "#D5BCC6",
      "muted": "#636773",
      "weakFill": "#DDDCDF",
      "weakFillStronger": "#C9CACE",
      "pageBg": "#FFFFFF",
      "pageLine": "#E2E3E5"
    }
  },
  {
    "key": "sequoia",
    "name": "Sequoia",
    "category": "Nature",
    "icon": "images/nature/sequoia-theme/icon48.png",
    "description": "Inspired by the towering presence and grounded calm of sequoias, this dark theme surrounds Chrome with rich woodland tones and subtle green life. It creates a focused, earthy atmosphere that feels steady, deep, and comfortably subdued.",
    "chromeUiUrl": "https://chromewebstore.google.com/detail/elbdggfmdikianlcniekopdflpkppnoj?utm_source=codigrate_extension",
    "preview": {
      "frame": "#394132",
      "toolbar": "#20231C",
      "accent": "#73A621",
      "frameText": "#F8FAFC",
      "toolbarText": "#F8FAFC",
      "activeTab": "#20231C",
      "inactiveTab": "#5D6357",
      "omnibox": "#3B3D37",
      "border": "#656B5F",
      "muted": "#979997",
      "weakFill": "#5C5F5B",
      "weakFillStronger": "#7B7D7A",
      "pageBg": "#292C25",
      "pageLine": "#636661"
    }
  },
  {
    "key": "autumn",
    "name": "Autumn",
    "category": "Nature",
    "icon": "images/nature/autumn-theme/icon48.png",
    "description": "Inspired by the warm hues and rustic charm of autumn, this light theme brings soft seasonal comfort to Chrome. Earthy oranges, mellow neutrals, and crisp contrast create a cozy browsing space that feels welcoming, balanced, and quietly expressive.",
    "chromeUiUrl": "https://chromewebstore.google.com/detail/fffebmlejekcghghcmiinjamjdcbbojc?utm_source=codigrate_extension",
    "preview": {
      "frame": "#EFE6E0",
      "toolbar": "#FCFBFA",
      "accent": "#A7714C",
      "frameText": "#0F172A",
      "toolbarText": "#0F172A",
      "activeTab": "#FCFBFA",
      "inactiveTab": "#D2CAC5",
      "omnibox": "#E8E7E6",
      "border": "#CEC6C1",
      "muted": "#626773",
      "weakFill": "#DBDBDD",
      "weakFillStronger": "#C8C9CC",
      "pageBg": "#FFFFFF",
      "pageLine": "#E2E3E5"
    }
  },
  {
    "key": "roraima",
    "name": "Roraima",
    "category": "Nature",
    "icon": "images/nature/roraima-theme/icon48.png",
    "description": "Inspired by the dramatic sunset over Mount Roraima, this dark theme blends dusky purples, ember-like oranges, and twilight shadows into a bold yet balanced browser palette. It brings warmth, depth, and a cinematic sense of atmosphere to everyday browsing.",
    "chromeUiUrl": "https://chromewebstore.google.com/detail/djgpkjnnddponeeeefijcpballhflkgd?utm_source=codigrate_extension",
    "preview": {
      "frame": "#372C2F",
      "toolbar": "#1E1A1B",
      "accent": "#CC654E",
      "frameText": "#F8FAFC",
      "toolbarText": "#F8FAFC",
      "activeTab": "#1E1A1B",
      "inactiveTab": "#5B5254",
      "omnibox": "#393536",
      "border": "#635A5D",
      "muted": "#969597",
      "weakFill": "#5B595A",
      "weakFillStronger": "#7A787A",
      "pageBg": "#272324",
      "pageLine": "#625F60"
    }
  },
  {
    "key": "istanbul",
    "name": "Istanbul",
    "category": "Cities",
    "icon": "images/cities/istanbul-theme/icon48.png",
    "description": "Inspired by the soft daylight and sea breezes of Istanbul, this theme brings airy turquoise tones and warm historical accents into Chrome. It feels fresh, calm, and expressive, offering a refined browsing atmosphere with a distinct coastal elegance.",
    "chromeUiUrl": "https://chromewebstore.google.com/detail/cjlcpahdceldmbpjbfglhmdlmonjhndf?utm_source=codigrate_extension",
    "preview": {
      "frame": "#91D1DA",
      "toolbar": "#FAFDFD",
      "accent": "#087E8E",
      "frameText": "#0F172A",
      "toolbarText": "#0F172A",
      "activeTab": "#FAFDFD",
      "inactiveTab": "#80B8C0",
      "omnibox": "#E6E9E9",
      "border": "#7DB4BB",
      "muted": "#616874",
      "weakFill": "#D9DDDF",
      "weakFillStronger": "#C6CACF",
      "pageBg": "#FFFFFF",
      "pageLine": "#E2E3E5"
    }
  },
  {
    "key": "miami",
    "name": "Miami",
    "category": "Cities",
    "icon": "images/cities/miami-theme/icon48.png",
    "description": "Inspired by the electric nights and pastel sunsets of Miami, this dark theme fills Chrome with bold purples, vivid pinks, tropical teals, and warm neon energy. It creates a playful yet polished browsing experience with strong personality and clear visual contrast.",
    "chromeUiUrl": "https://chromewebstore.google.com/detail/kcmjhfhghepidmmaklccljefhjgfnlbc?utm_source=codigrate_extension",
    "preview": {
      "frame": "#5D263A",
      "toolbar": "#33121D",
      "accent": "#FF5FA2",
      "frameText": "#F8FAFC",
      "toolbarText": "#F8FAFC",
      "activeTab": "#33121D",
      "inactiveTab": "#7A4D5D",
      "omnibox": "#4B2E38",
      "border": "#815665",
      "muted": "#9F9298",
      "weakFill": "#6A535B",
      "weakFillStronger": "#86737B",
      "pageBg": "#3B1B26",
      "pageLine": "#705962"
    }
  },
  {
    "key": "rio-de-janeiro",
    "name": "Rio de Janeiro",
    "category": "Cities",
    "icon": "images/cities/rio-de-janeiro-theme/icon48.png",
    "description": "Inspired by Rio's lush hills, bright air, and coastal energy, this theme blends soft minty tones with vibrant greens and clean blues to create a light, refreshing Chrome experience that feels lively, open, and balanced.",
    "chromeUiUrl": "https://chromewebstore.google.com/detail/docafppdkimloimielffokjbnpfjaaie?utm_source=codigrate_extension",
    "preview": {
      "frame": "#94B98B",
      "toolbar": "#F7FAF6",
      "accent": "#375B2E",
      "frameText": "#F8FAFC",
      "toolbarText": "#0F172A",
      "activeTab": "#F7FAF6",
      "inactiveTab": "#82A37A",
      "omnibox": "#E3E6E2",
      "border": "#7F9F78",
      "muted": "#606671",
      "weakFill": "#D7DAD9",
      "weakFillStronger": "#C4C8C9",
      "pageBg": "#FFFFFF",
      "pageLine": "#E2E3E5"
    }
  },
  {
    "key": "paris",
    "name": "Paris",
    "category": "Cities",
    "icon": "images/cities/paris-theme/icon48.png",
    "description": "Inspired by candlelit cafes, stone boulevards, and Paris's late-night glow, this theme brings dusky rose, plum-espresso depth, and soft blush accents into Chrome. It feels romantic, moody, and elegant without losing clarity.",
    "chromeUiUrl": "https://chromewebstore.google.com/detail/jcneihnpahfoamjdncacanalmdiokkbj?utm_source=codigrate_extension",
    "preview": {
      "frame": "#564245",
      "toolbar": "#271F20",
      "accent": "#D39199",
      "frameText": "#F8FAFC",
      "toolbarText": "#F8FAFC",
      "activeTab": "#271F20",
      "inactiveTab": "#746466",
      "omnibox": "#413A3B",
      "border": "#7B6C6E",
      "muted": "#9A9799",
      "weakFill": "#625C5E",
      "weakFillStronger": "#7F7B7C",
      "pageBg": "#302829",
      "pageLine": "#686364"
    }
  },
  {
    "key": "tallinn",
    "name": "Tallinn",
    "category": "Cities",
    "icon": "images/cities/tallinn-theme/icon48.png",
    "description": "Inspired by Tallinn's crisp light and Baltic calm, this theme pairs cool porcelain tones with Nordic blues for a browser experience that feels clean, minimal, and quietly elegant. Subtle contrast keeps everything fresh and readable.",
    "chromeUiUrl": "https://chromewebstore.google.com/detail/efehigdahohhplollagfpnleobcaknpc?utm_source=codigrate_extension",
    "preview": {
      "frame": "#A9B9DA",
      "toolbar": "#EDF2FA",
      "accent": "#3F4494",
      "frameText": "#0F172A",
      "toolbarText": "#0F172A",
      "activeTab": "#EDF2FA",
      "inactiveTab": "#95A3C0",
      "omnibox": "#DADFE6",
      "border": "#919FBB",
      "muted": "#5D6473",
      "weakFill": "#CED3DD",
      "weakFillStronger": "#BCC2CC",
      "pageBg": "#FFFFFF",
      "pageLine": "#E2E3E5"
    }
  },
  {
    "key": "tokyo",
    "name": "Tokyo",
    "category": "Cities",
    "icon": "images/cities/tokyo-theme/icon48.png",
    "description": "Inspired by Tokyo's neon-lit streets and midnight skyline, this theme surrounds Chrome with deep indigo tones, electric violets, and cool luminous accents. It feels sleek, atmospheric, and distinctly futuristic while staying polished.",
    "chromeUiUrl": "https://chromewebstore.google.com/detail/glgifonajfdadakpjjndpfnmmlaoeglb?utm_source=codigrate_extension",
    "preview": {
      "frame": "#323B66",
      "toolbar": "#1A1F35",
      "accent": "#7285DC",
      "frameText": "#F8FAFC",
      "toolbarText": "#F8FAFC",
      "activeTab": "#1A1F35",
      "inactiveTab": "#575E82",
      "omnibox": "#353A4D",
      "border": "#5F6688",
      "muted": "#9497A2",
      "weakFill": "#585C6D",
      "weakFillStronger": "#777B89",
      "pageBg": "#23283D",
      "pageLine": "#5F6372"
    }
  }
];

function getThemeByKey(themeKey) {
  const theme = THEMES.find(theme => theme.key === themeKey);
  if (theme) return theme;
  return THEMES.find(theme => theme.key === 'everest') || THEMES[0];
}
